### ISSUE TITLE
[BUG][Tournament-v4] Stats callbacks are not being sent after completed matches

### ISSUE THREAD

**Issue by zoltanzseli** [RiotGames/developer-relations#689]
Summary
We stopped receiving callbacks from the RIOT API after games were played today (2022.10.08). We only received 2 interrupted match statistics, therefore I think the issue is not on our side.

Steps to Reproduce

Generate a tournamentId w/ a valid callback URL that can receive callbacks
Play a game with t-codes
Notice that the callback does not come via the valid URL

Expected Result
Expecting a callback from RIOT w/ stats to the callback URL provided

Actual Result
We are not receiving callbacks after games are played.

Reproduction Rate
100% (16/16)

Notes:
Please let me know if you'd like me to reproduce it on demand.

Severity:
High

**Comment by LeonBirkel** [comment]
I have a similar issue. A callback is trriggerd for me, but it is empty. 
If I use the cURL from the developer portal to mimic the behavior of the callback, everything works fine.

**Comment by diogohy** [comment]
I play league tournaments in Brazil, and its so irritating to play the games, and have to wait sometimes up to 10 minutes just to the organizer make the changes manually to the brackets, just because of this bug, why does it take so long to fix aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by thomasmarton** [comment]
@diogohy I'm kind of sorry to break it down, but I highly doubt there is any interest inside of riot to even start the fix so your comment might be phrased wrong

We used to have a meme on the developer discord that we don't provide enough player value to warrant certain features being added to the API. I'm using the word "used to" cause it became a reality, it's no longer a meme.

I'm afraid that unless Riot has a need for this service internally (clash was developed from scratch so I wouldn't be hopeful), it won't receive any updates/bugfixes (last time it was touched was most likely around 2018 when they had to remove the raw IDs, when match-v5 received new IDs, they didn't feel necessary to update the callback)

**Comment by LeonBirkel** [comment]
> I have a similar issue. A callback is trriggerd for me, but it is empty. If I use the cURL from the developer portal to mimic the behavior of the callback, everything works fine.

My problem at the time was that I was using a newer SSL certificate. 
If I run the callback via http, I no longer get any repsonse. 
So yes, I actully have the exact same issue :D ^^

**Comment by fireinnti** [comment]
Also started having issues with tourny callbacks last few days with no changes on my production environment for weeks. Just throwing that in there.

**Comment by zoltanzseli** [comment]
Same result (I mean no result) today.

**Comment by HenrySpartGlobal** [comment]
@zoltanzseli @fireinnti - I may be having similar issues, but I am brand new to this whole thing so there could be holes in my testing. Is it okay if I could ask you some questions, not sure what is the best way to contact you. Maybe discord. want to make sure it is not my testing and the best way to find out is by asking people who have got it working in the past. 

My discord 
iHenners#1234

**Comment by RicardoNito** [comment]
give them year or two to fix it. Problem with pause tournament games on EUNE server be already in "fix" half year :D
So Riot Games will not repair it and kill all tournaments platforms XD? Nice step to develop ecosystem

**Comment by riotstillrampant** [comment]
The League team deployed a potential fix for this in the most recent patch. Please confirm here if the issue has resolved or not.

**Comment by fireinnti** [comment]
@riotstillrampant it has started working for me today. Thanks for your/other devs help

**Comment by zoltanzseli** [comment]
> give them year or two to fix it. Problem with pause tournament games on EUNE server be already in "fix" half year :D So Riot Games will not repair it and kill all tournaments platforms XD? Nice step to develop ecosystem

This attitude never helps. We don't see what happens behind the scene, I mean the issue that causes this problem could be hard to fix.

**Comment by LeonBirkel** [comment]
@riotstillrampant I still have problems. I receive callbacks but without content. 
I have tested the process alone by starting a match against a bot and immediately leaving the game. 

I don't know if content should be transferred at all in this case. I will create new codes in the next few days and finish a game. 

Me alone against bots in a 5vs5 lobby is not a problem for the callback?

**Comment by zoltanzseli** [comment]
> The League team deployed a potential fix for this in the most recent patch. Please confirm here if the issue has resolved or not.

Hey, it works now. Thank you!

**Comment by LeonBirkel** [comment]
> > The League team deployed a potential fix for this in the most recent patch. Please confirm here if the issue has resolved or not.
> 
> Hey, it works now. Thank you!

Can you help me out and tell me how you test the callbacks ?

**Comment by thomasmarton** [comment]
> > give them year or two to fix it. Problem with pause tournament games on EUNE server be already in "fix" half year :D So Riot Games will not repair it and kill all tournaments platforms XD? Nice step to develop ecosystem
> 
> This attitude never helps. We don't see what happens behind the scene, I mean the issue that causes this problem could be hard to fix.

We do see what happens behind the scenes. This very service doesn't support SSL CAs/domain TLDs newer than 2012/2011 respectively because we don't provide enough player value to have support for simple things like LetsEncrypt (so that we wouldn't have to pay for SSL certificates)

Or you can check the documentation for match-v5 which is something people have been asking for, but it's been in progress ever since the API came out, but to no avail.

We are way past the "attitude" problem

**Comment by Token07** [comment]
> @riotstillrampant I still have problems. I receive callbacks but without content. I have tested the process alone by starting a match against a bot and immediately leaving the game.
> 
> I don't know if content should be transferred at all in this case. I will create new codes in the next few days and finish a game.
> 
> Me alone against bots in a 5vs5 lobby is not a problem for the callback?

Ending the game that early is more than likely the issue. Try running a game until completion, or at least longer than a few minutes, and please report back, though based on other responses it sounds like it is resolved.

**Comment by HenrySpartGlobal** [comment]
@LeonBirkel - I have found that if you play around 3 minutes with bots 5v5, you should get a callback. If that call back works then it should all be fine. I don't think leaving straight away will work, but I've not tested it myself.

**Comment by lucasMesquitaBorges** [comment]
Hi, as @riotstillrampant mentioned, this issue was tackled on the last release. Thanks everyone who helped in the verification.

@LeonBirkel as @Token07 mentioned, you received an empty callback due to leaving the game so early. Before the error being fixed the callback was not being sent.

I will close this issue, in any case needed, feel free to open a new one.

**Comment by LeonBirkel** [comment]
> @LeonBirkel - I have found that if you play around 3 minutes with bots 5v5, you should get a callback. If that call back works then it should all be fine. I don't think leaving straight away will work, but I've not tested it myself.

Thanks, I tired more things now, I even played games until the end with 9 bots. 
I do get a callback, but it is empty.

**Comment by LeonBirkel** [comment]
> > @riotstillrampant I still have problems. I receive callbacks but without content. I have tested the process alone by starting a match against a bot and immediately leaving the game.
> > I don't know if content should be transferred at all in this case. I will create new codes in the next few days and finish a game.
> > Me alone against bots in a 5vs5 lobby is not a problem for the callback?
> 
> Ending the game that early is more than likely the issue. Try running a game until completion, or at least longer than a few minutes, and please report back, though based on other responses it sounds like it is resolved.

Ah sorry, I marked the wrong comment. 
I still have issues. I get a callback without data after a match is completed. 

I am using a http callback URL and playing with 4 bots in my team against 5 bots in my opponent team. 
When I call the callback test everything works, since the test callback is from my localhost and I get an empty response from League, I think a problem in my code is unlikely. 

But to make things clear, I only joined 3 weeks ago and have therefore never received a valid callback ^^ At that time there was already the problem with the update.

**Comment by zoltanzseli** [comment]
Today we faced this issue again.
